# Generated by Django 4.2.1 on 2023-07-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(default='up', max_length=5)),
                ('status', models.CharField(default='idle', max_length=10)),
            ],
        ),
    ]
