# Generated by Django 4.2.1 on 2023-07-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='door_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elevator',
            name='operational',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevatorapp.elevator')),
            ],
        ),
    ]
